// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFiVnqQorJ5V2adK7Skn3Czp5AQdWAaAA',
    appId: '1:681904136683:web:1efd5062687709fb1ef9ae',
    messagingSenderId: '681904136683',
    projectId: 'afriendorsehq',
    authDomain: 'afriendorsehq.firebaseapp.com',
    storageBucket: 'afriendorsehq.firebasestorage.app',
    measurementId: 'G-SEBKF3PBVF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvUg-AJpYsei4s2XacN7L69F9I8HVNsk0',
    appId: '1:681904136683:android:2c633defe07b97c51ef9ae',
    messagingSenderId: '681904136683',
    projectId: 'afriendorsehq',
    storageBucket: 'afriendorsehq.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6MRjAXVyv0MIv4XpeGMqX_Wb894WHzQc',
    appId: '1:681904136683:ios:c2291e2a8a225db81ef9ae',
    messagingSenderId: '681904136683',
    projectId: 'afriendorsehq',
    storageBucket: 'afriendorsehq.firebasestorage.app',
    iosBundleId: 'com.afriendorse.user',
  );
}
